=== codeaudit/cougaar-cougaarlegacy/coabs/configs/tasc/AEFALLOCATIONS.dtd
<!ELEMENT AEFALLOCATIONS (ALLOCATIONITEM+)>
<!ATTLIST AEFALLOCATIONS
	AEF CDATA #REQUIRED>
<!ELEMENT ALLOCATIONITEM EMPTY>
<!ATTLIST ALLOCATIONITEM
	taskid 	CDATA #REQUIRED
	requestor	CDATA #REQUIRED
	supplier	CDATA #REQUIRED
 	asset	 	CDATA #REQUIRED
	NSN		CDATA #REQUIRED
	quantity 	CDATA #REQUIRED>

=== codeaudit/cougaar-cougaarlegacy/coabs/configs/tasc/AEFALLOCATIONS.xml
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE AEFALLOCATIONS SYSTEM "AEFALLOCATIONS.dtd">
<AEFALLOCATIONS AEF="AEF1">
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
	<ALLOCATIONITEM
		taskid = "asdf"
		requestor = "421FS"
		supplier = "WRM"
		asset = "N2 Lite Cart"
		NSN = "12345"
		quantity = "5"/>
